<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta name="viewport" content="width=device-width" /><title>https://cli.im/news/xmlrpc.php?rsd</title><link rel="stylesheet" type="text/css" href="resource://content-accessible/viewsource.css" /></head><body id="viewsource" class="highlight" style="-moz-tab-size: 4" contextmenu="actions"><pre id="line1"><span>
<span id="line2"></span></span><span class="pi">&lt;?xml version="1.0" encoding="UTF-8"?&gt;</span><span></span><span>&lt;<span class="start-tag">rsd</span> <span class="attribute-name">version</span>="<a class="attribute-value">1.0</a>" <span class="attribute-name">xmlns</span>="<a class="attribute-value">http://archipelago.phrasewise.com/rsd</a>"&gt;</span><span>
<span id="line3"></span>  </span><span>&lt;<span class="start-tag">service</span>&gt;</span><span>
<span id="line4"></span>    </span><span>&lt;<span class="start-tag">engineName</span>&gt;</span><span>WordPress</span><span>&lt;/<span class="end-tag">engineName</span>&gt;</span><span>
<span id="line5"></span>    </span><span>&lt;<span class="start-tag">engineLink</span>&gt;</span><span>https://wordpress.org/</span><span>&lt;/<span class="end-tag">engineLink</span>&gt;</span><span>
<span id="line6"></span>    </span><span>&lt;<span class="start-tag">homePageLink</span>&gt;</span><span>http://cli.im/news</span><span>&lt;/<span class="end-tag">homePageLink</span>&gt;</span><span>
<span id="line7"></span>    </span><span>&lt;<span class="start-tag">apis</span>&gt;</span><span>
<span id="line8"></span>      </span><span>&lt;<span class="start-tag">api</span> <span class="attribute-name">name</span>="<a class="attribute-value">WordPress</a>" <span class="attribute-name">blogID</span>="<a class="attribute-value">1</a>" <span class="attribute-name">preferred</span>="<a class="attribute-value">true</a>" <span class="attribute-name">apiLink</span>="<a class="attribute-value">http://cli.im/news/xmlrpc.php</a>" <span>/</span>&gt;</span><span>
<span id="line9"></span>      </span><span>&lt;<span class="start-tag">api</span> <span class="attribute-name">name</span>="<a class="attribute-value">Movable Type</a>" <span class="attribute-name">blogID</span>="<a class="attribute-value">1</a>" <span class="attribute-name">preferred</span>="<a class="attribute-value">false</a>" <span class="attribute-name">apiLink</span>="<a class="attribute-value">http://cli.im/news/xmlrpc.php</a>" <span>/</span>&gt;</span><span>
<span id="line10"></span>      </span><span>&lt;<span class="start-tag">api</span> <span class="attribute-name">name</span>="<a class="attribute-value">MetaWeblog</a>" <span class="attribute-name">blogID</span>="<a class="attribute-value">1</a>" <span class="attribute-name">preferred</span>="<a class="attribute-value">false</a>" <span class="attribute-name">apiLink</span>="<a class="attribute-value">http://cli.im/news/xmlrpc.php</a>" <span>/</span>&gt;</span><span>
<span id="line11"></span>      </span><span>&lt;<span class="start-tag">api</span> <span class="attribute-name">name</span>="<a class="attribute-value">Blogger</a>" <span class="attribute-name">blogID</span>="<a class="attribute-value">1</a>" <span class="attribute-name">preferred</span>="<a class="attribute-value">false</a>" <span class="attribute-name">apiLink</span>="<a class="attribute-value">http://cli.im/news/xmlrpc.php</a>" <span>/</span>&gt;</span><span>
<span id="line12"></span>      	</span><span>&lt;<span class="start-tag">api</span> <span class="attribute-name">name</span>="<a class="attribute-value">WP-API</a>" <span class="attribute-name">blogID</span>="<a class="attribute-value">1</a>" <span class="attribute-name">preferred</span>="<a class="attribute-value">false</a>" <span class="attribute-name">apiLink</span>="<a class="attribute-value">http://cli.im/news/wp-json/</a>" <span>/</span>&gt;</span><span>
<span id="line13"></span>	    </span><span>&lt;/<span class="end-tag">apis</span>&gt;</span><span>
<span id="line14"></span>  </span><span>&lt;/<span class="end-tag">service</span>&gt;</span><span>
<span id="line15"></span></span><span>&lt;/<span class="end-tag">rsd</span>&gt;</span><span>
<span id="line16"></span></span></pre><menu type="context" id="actions"><menuitem id="goToLine" label="转到指定行…" accesskey="L"></menuitem><menuitem id="wrapLongLines" label="长行自动换行" type="checkbox"></menuitem><menuitem id="highlightSyntax" label="语法高亮" type="checkbox" checked="true"></menuitem></menu></body></html>